# conda environment description file for NEMO_Nowcast package testing environment
#
# Creates a conda environment in which the NEMO_Nowcast package unit tests and
# coverage analysis can be run.
# Primarily intended for creation of a conda env for use in a GitHub Actions workflow.

name: nemo-nowcast-test

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - pip
  - PyYAML
  - pyzmq
  - requests
  - schedule
  - sentry-sdk
  - supervisor

  # For unit tests
  - pytest
  - pytest-cov
  - pytest-randomly

  # For documentation link checking
  - sphinx
  - sphinx_rtd_theme=1.1.1

  - pip:
    # install of NEMO_Nowcast package in editable mode
    - --editable ./
