# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - defaults

dependencies:
  - arrow
  - attrs
  - python>=3.6
  - pyyaml
  - pyzmq
  - sentry-sdk

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
