# conda environment description file for NEMO_Nowcast package
# development environment
#
# Create a conda environment for development, testing, and documentation
# of the NEMO Nowcast framework with:
#
#    $ conda env create -f NEMO_Nowcast/environment-dev.yaml
#    $ source activate nemo-nowcast

name: nemo-nowcast

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - pip
  - python=3.12
  - PyYAML
  - pyzmq
  - requests
  - sentry-sdk
  - supervisor
  - schedule

  # For coding style
  - black

  # For unit tests
  - pytest
  - pytest-cov
  - pytest-randomly

  # For documentation
  - sphinx=8.1.3
  - sphinx-rtd-theme=3.0.0

  - pip:
    # install of NEMO_Nowcast package in editable mode
    - --editable ./
