# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - defaults

dependencies:
  - python=3.6

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
