# conda environment description file for docs build environment
# on readthedocs.org

name: sphinx-build

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - pip
  - python=3.11
  - pyyaml
  - pyzmq
  - schedule
  - sentry-sdk
  - supervisor

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme=1.1.1

  - pip:
    # install of NEMO_Nowcast package in editable mode
    - --editable ./
