# conda environment description file for docs build environment
# on readthedocs.org

name: nemo-nowcast-docs

channels:
  - conda-forge
  - nodefaults

dependencies:
  - arrow
  - attrs
  - pip
  - python=3.12
  - pyyaml
  - pyzmq
  - schedule
  - sentry-sdk
  - supervisor

  # RTD packages
  - mock
  - pillow
  - sphinx=8.1.3
  - sphinx-rtd-theme=3.0.0

  - pip:
    # install of NEMO_Nowcast package in editable mode
    - --editable ./
