name: Add Milestone to Issue/PR

permissions: {}

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  add_milestone:
    permissions:
      issues: write  # Required for adding milestones to issues
      pull-requests: write  # Required for adding milestones to pull requests
    uses: UBC-MOAD/gha-workflows/.github/workflows/auto-milestone-issue-pr.yaml@main  # zizmor: ignore[unpinned-uses]
