name: CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test-coverage:
    name: pytest & coverage report
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6']

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           auto-update-conda: true
           activate-environment: nemo-nowcast
           environment-file: environment-dev.yaml
           python-version: ${{ matrix.python-version }}
           auto-activate-base: false

      - name: Install package
        shell: bash -l {0}
        run: python3 -m pip install --editable $GITHUB_WORKSPACE

      - name: pytest package with coverage
        shell: bash -l {0}
        run: coverage run -m pytest --junitxml=./test-reports/junit.xml

      - name: coverage report
        shell: bash -l {0}
        run: coverage report
