name: pytest-with-coverage

permissions: {}

on:
  push:
    branches: [ '*' ]
  # Enable workflow to be triggered from GitHub CLI, browser, or via API
  # primarily for testing conda env solution for new Python versions
  workflow_dispatch:

jobs:
  pytest-with-coverage:
    permissions:
      contents: read  # Required to access repository contents for testing
      pull-requests: write  # Required to upload code coverage to pull requests

    strategy:
      fail-fast: false
      matrix:
        environment: [ 'test-py312', 'test-py313', 'test-py314' ]

    uses: UBC-MOAD/gha-workflows/.github/workflows/pixi-pytest-with-coverage.yaml@main  # zizmor: ignore[unpinned-uses]
    with:
      environment: ${{ matrix.environment }}

    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
