name: sphinx-linkcheck

permissions: {}

on:
  push:
    branches: [ '*' ]
  schedule:
    - cron: 43 12 15 * *  # 12:43 UTC on the 15th day of each month

jobs:
  sphinx-linkcheck:
    name: Sphinx linkcheck
    permissions:
      contents: read  # Required to access repository contents for link checking

    uses: UBC-MOAD/gha-workflows/.github/workflows/pixi-sphinx-linkcheck.yaml@main  # zizmor: ignore[unpinned-uses]
